### ISSUE TITLE
Wish: Option to clamp scrubbing to set timeline range

### ISSUE THREAD

**Issue by LarsJandel** [Pullusb/viewport_timeline_scrub#1]
Hi, first of all thanks for implementing this, just fantastic! 🙏
Would it be possible to have an option to clamp the scrubbing to the timeline range? For example, if I have a range from frame 25-50, the scrubbing would stop either on the first frame (25) or last frame (50) of the range. It's great, that the range is already displayed in the UI of course! 👍
As said, if possible just as an option, so users can decide to use clamping or not.

Thanks!

**Comment by Pullusb** [comment]
Hi, Thank you for your feedback.
Make sense. if added, it will not be a separated option though, just respect the already existing toggle `playback > limit to frame range`.

**Comment by LarsJandel** [comment]
To be honest, I didn't know / used that toggle before as the clamping just came via scrubbing to my mind. Just tried it and you are right, it would be great if it would respect that toggle. That would have the desired effect indeed. Thanks!

**Comment by Pullusb** [comment]
This is now added on this repository and also on `Grease pencil tools` in the next blender 2.93 daily build.
Closing the Thread, feel free to reopen if you find any bugs.

**Comment by LarsJandel** [comment]
Yes, just installed the latest 2.93 and it works as wished for having the corresponding toggle set - thanks for this quick enhancement! 🙏
