### ISSUE TITLE
blender 3.4 snap error

### ISSUE THREAD

**Issue by ganim3d** [Pullusb/viewport_timeline_scrub#5]
gets an error of float instead of int when snapping to frame
some changes to work
440: context.scene.frame_current = int(self.new_frame)
443: self.offset = int(self.new_frame - self.init_frame)

**Comment by Pullusb** [comment]
Hi, this repository is not up to date since _Timelinescrub_ is already integrated and maintained in Grease Pencil Tools (shipped with blender).
